" Settings related to pathogen
execute pathogen#infect()
syntax on
filetype on
filetype plugin on
filetype indent on

" Set Color Scheme
color Monokai

"---> Settings specific to python development <---

set number  " show line numbers
set ts=4  " set tabs to have 4 spaces

" expand tabs into spaces
set expandtab
set shiftwidth=4
set tabstop=4

set cursorline  " show a visual line under cursor's current line
set showmatch  " show the matching part of the pair for {} [] ()

let python_highlight_all = 1  " enable all python syntax highlighting features

" ---> End specific settings to python development <---

" ---> Some Basic Config <---

set encoding=utf-8
set nocompatible
set history=999
set autoindent 
set smartindent 
set wrap
set copyindent
set incsearch
set ignorecase
set smartcase
set autoread  " set to auto read when a file is changed from outside
set cmdheight=2  " height of the command bar
set ruler  " always show current position
set magic  " turn magic on for regular expressions
set hlsearch  " search highlighting
set laststatus=2  " always show the status line
set backspace=eol,start,indent

" ---> End Basic Config <---

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Copy to system clipboard
set clipboard+=unnamed
set paste

" Settings turned on for formating code every time a buffer is written
" rust.vim
let g:rustfmt_autosave = 1
